apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wjy92lztz-go
  janus-idp.io/tekton: wjy92lztz-go
  backstage.io/kubernetes-id: wjy92lztz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wjy92lztz-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
